site_name: cloud.gov.au documentation
site_url: http://docs.cloud.gov.au
repo_url: https://github.com/AusDTO/cga_docs
site_description: "Documentation for users of cloud.gov.au"
theme: gov-au-theme
google_analytics: ['UA-61222473-5', 'auto']
extra:
  search: true
  footer_links:
    - 'title': 'Status'
      'url': 'http://status.cloud.gov.au/'
      'external': 'true'
markdown_extensions:
  - toc:
pages:
  - Home: index.md
  - Getting started:
    - 'Setup a new project': 'getting_started/new_project.md'
    - 'Install command line tools': 'getting_started/install_cli.md'
    - 'Login': 'getting_started/login.md'
    - 'Get an app ready for launch': 'getting_started/orca.md'
  - Deployment and configuration:
    - 'Application deployment': 'deployment_configuration/application_deployment.md'
    - 'Application deletion': 'deployment_configuration/application_delete.md'
    - 'Setup Continuous deployment': 'deployment_configuration/ci_cd.md'
    - 'Setup CircleCI': 'deployment_configuration/setup_circle.md'
    - 'Create manifest.yml': 'deployment_configuration/create_manifest.md'
    - 'Zero downtime deploys': 'deployment_configuration/zero_downtime_deploys.md'
    - 'Deploying feature branches': 'deployment_configuration/deploying_feature_branches.md'
  - Services:
    - 'Sending Emails': 'services/sending_emails.md'
    - 'Log access': 'services/log_access.md'
  - Support:
    - 'Incident response': 'support/incident_response.md'
    - 'Incident reports': 'support/incident_reports.md'
    - '_2016-08-12': 'support/incident_reports/2016-08-12.md'
    - '_2016-06-05': 'support/incident_reports/2016-06-05.md'
    - '_2016-02-11': 'support/incident_reports/2016-02-11.md'
