site_name: cloud.gov.au
site_url: http://docs.cloud.gov.au
site_description: "Documentation for users of cloud.gov.au"
theme: gov-au-theme
google_analytics: ['UA-61222473-5', 'auto']
extra:
  search: true
  footer_links:
    - 'title': 'Status'
      'url': 'http://status.cloud.gov.au/'
      'external': 'true'
markdown_extensions:
  - toc:
pages:
  - Home: index.md
  - Usage:
    - 'Setup a new project': 'usage/start_new_project.md'
    - 'Install command line tools': 'usage/setup.md'
    - 'Login and target your project': 'usage/login.md'
    - 'Sending Emails': 'usage/sending_emails.md'
    - 'Your First Deploy': 'usage/your_first_deploy.md'
    - 'Getting your app ready for launch': 'usage/orca.md'
    - 'Setup CircleCI': 'usage/setup_circle.md'
  - CF-CLI:
    - 'Intro': usage/cfcli/index.md
    - 'Application Deployment': usage/cfcli/application_deployment.md
    - 'Application Deletion': usage/cfcli/application_delete.md
    - 'Log Access': usage/cfcli/log_access.md
  - Support:
    - 'Incident response': 'support/incident_response.md'
  - 'Incident reports':
    - 'Intro': 'support/incident_reports/index.md'
    - '2016-08-12': 'support/incident_reports/2016-08-12.md'
    - '2016-06-05': 'support/incident_reports/2016-06-05.md'
    - '2016-02-11': 'support/incident_reports/2016-02-11.md'
